# Uncomment these two line to add support for encoders to your firmware
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the following line to enable the Kyria OLED Display
# CONFIG_ZMK_DISPLAY=y

# Uncomment the following lines to enable RGB underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_PERIPHERAL=y

CONFIG_ZMK_SLEEP=y

CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_PMW3610_ALT=y
CONFIG_ZMK_POINTING=y

# CONFIG_PMW3610_SWAP_XY=y
# CONFIG_PMW3610_INVERT_X=y
#CONFIG_PMW3610_INVERT_Y=y
#CONFIG_PMW3610_SMART_ALGORITHM=y
###CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=30

# Idle State: 2 min
#CONFIG_ZMK_IDLE_TIMEOUT=120000
# Deep Sleep: 30 min
#CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

CONFIG_ZMK_EXT_POWER=y

##CONFIG_ZMK_MOUSE=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

#CONFIG_PMW3610_SWAP_XY=y

# Turn on logging, and set ZMK logging to debug output
CONFIG_ZMK_USB_LOGGING=y
CONFIG_LOG=y
CONFIG_ZMK_LOG_LEVEL_DBG=y
